### ISSUE TITLE
[PE-D] Lesson disappeared just like how task disappeared

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-3/tp#153] opened 2021-10-30 18:57 UTC
![image.png](https://raw.githubusercontent.com/uosjapuelks/ped/main/files/ab10a014-3c6c-44a3-abb1-951b870dedaa.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: uosjapuelks/ped#23

**Comment by richwill28** [comment] 2021-10-31 02:49
A duplicate of #134.

**Closed** 2021-10-31 09:08 UTC
Labels: severity.Medium, priority.High, type.Bug
