### ISSUE TITLE
[PE-D] UG formatting confusing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-3/tp#126] opened 2021-10-30 15:04 UTC
![image.png](https://raw.githubusercontent.com/uosjapuelks/ped/main/files/a27191a0-a914-41c4-80c0-8ac79eb01c65.png)

In is bolded but the list below has no bolded marker. Confusing

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: uosjapuelks/ped#9

**Comment by richwill28** [comment] 2021-10-30 17:17
A duplicate of #118.

**Closed** 2021-10-31 01:31 UTC
Labels: severity.VeryLow, type.Bug
